spring:
  profiles:
    active: local

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  packages-to-scan: com.zb.fresh_api.api
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false
  enable-kotlin: false

api:
  kakao:
    kauth: https://kauth.kakao.com
    kapi: https://kapi.kakao.com

