spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/fresh
    username: root
    password: root
# swagger
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  packages-to-scan: com.zb.fresh_api.api
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false
  enable-kotlin: false
