#spring:
#  config:
#    import: aws-parameterstore:/param/fresh2you_${spring.profiles.active}/

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  packages-to-scan: com.zb.fresh_api.api
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false
  enable-kotlin: false

api:
  kakao:
    kauth: https://kauth.kakao.com
    kapi: https://kapi.kakao.com

  websocket:
    enabled: true
    stomp:
      enabled: true
      endpoint: /ws
      allowed-origins:
        - http://localhost:3000
        - https://localhost:3000
        - http://localhost:8080
        - https://localhost:8080
        - http://api.jihun-dev.kr
        - https://api.jihun-dev.kr
    broker:
      relay:
        enabled: true
        destination-prefixes:
          - /app
          - /topic

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
