-- 형용사 (ADJECTIVE) 삽입
INSERT INTO word (word, type) VALUES
                                           ('빠른', 'ADJECTIVE'),
                                           ('느린', 'ADJECTIVE'),
                                           ('영리한', 'ADJECTIVE'),
                                           ('귀여운', 'ADJECTIVE'),
                                           ('힘찬', 'ADJECTIVE'),
                                           ('용감한', 'ADJECTIVE'),
                                           ('행복한', 'ADJECTIVE'),
                                           ('슬픈', 'ADJECTIVE'),
                                           ('화난', 'ADJECTIVE'),
                                           ('사나운', 'ADJECTIVE'),
                                           ('조용한', 'ADJECTIVE'),
                                           ('활발한', 'ADJECTIVE'),
                                           ('부드러운', 'ADJECTIVE'),
                                           ('단단한', 'ADJECTIVE'),
                                           ('창의적인', 'ADJECTIVE'),
                                           ('유쾌한', 'ADJECTIVE'),
                                           ('정직한', 'ADJECTIVE'),
                                           ('따뜻한', 'ADJECTIVE'),
                                           ('냉정한', 'ADJECTIVE'),
                                           ('재미있는', 'ADJECTIVE');

-- 명사 (NOUN) 삽입
INSERT INTO word (word, type) VALUES
                                           ('호랑이', 'NOUN'),
                                           ('토끼', 'NOUN'),
                                           ('사자', 'NOUN'),
                                           ('곰', 'NOUN'),
                                           ('여우', 'NOUN'),
                                           ('고양이', 'NOUN'),
                                           ('강아지', 'NOUN'),
                                           ('늑대', 'NOUN'),
                                           ('판다', 'NOUN'),
                                           ('부엉이', 'NOUN'),
                                           ('고래', 'NOUN'),
                                           ('원숭이', 'NOUN'),
                                           ('독수리', 'NOUN'),
                                           ('돌고래', 'NOUN'),
                                           ('사슴', 'NOUN'),
                                           ('양', 'NOUN'),
                                           ('치타', 'NOUN'),
                                           ('거북이', 'NOUN'),
                                           ('까마귀', 'NOUN'),
                                           ('코끼리', 'NOUN');
